import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';

import {
  MatSidenavModule,
  MatToolbarModule,
  MatButtonModule,
  MatDatepickerModule,
  MatButtonToggleModule,
  MatTableModule,
  MatChipsModule,
  MatInputModule,
  MatSelectModule,
  MatIconModule,
  MatListModule,
  MatPaginatorModule,
  MatSortModule,
  MatSnackBarModule,
  MatCardModule,
  MatDialogModule,
  MatGridListModule,
  MatCheckboxModule,
  MatStepperModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatMenuModule,
  MatTooltipModule,
  MatRadioModule,
  MatBottomSheetModule
} from '@angular/material';

@NgModule({
  declarations: [],
  imports: [
    CommonModule,
    MatSidenavModule,
  MatToolbarModule,
  MatButtonModule,
  MatDatepickerModule,
  MatButtonToggleModule,
  MatTableModule,
  MatChipsModule,
  MatInputModule,
  MatSelectModule,
  MatIconModule,
  MatListModule,
  MatPaginatorModule,
  MatSortModule,
  MatSnackBarModule,
  MatCardModule,
  MatDialogModule,
  MatGridListModule,
  MatCheckboxModule,
  MatStepperModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatMenuModule,
  MatTooltipModule,
  MatRadioModule,
  MatBottomSheetModule
  ],
  exports: [
    MatSidenavModule,
  MatToolbarModule,
  MatButtonModule,
  MatDatepickerModule,
  MatButtonToggleModule,
  MatTableModule,
  MatChipsModule,
  MatInputModule,
  MatSelectModule,
  MatIconModule,
  MatListModule,
  MatPaginatorModule,
  MatSortModule,
  MatSnackBarModule,
  MatCardModule,
  MatDialogModule,
  MatGridListModule,
  MatCheckboxModule,
  MatStepperModule,
  MatSliderModule,
  MatSlideToggleModule,
  MatMenuModule,
  MatTooltipModule,
  MatRadioModule,
  MatBottomSheetModule
  ]
})
export class MaterialModule { }
